# Site settings
title: Steve Frost - Full Stack Web Developer
description: "Full-Stack Web Developer. Urban Fixed Cyclist. Hugger of Trees."
baseurl: ""
url: "https://steveafrost.com"

# User settings
username: Steve Frost
user_title: Full-Stack Web Developer
email: hello@steveafrost.com
twitter_username: SteveEff
github_username:  steveafrost
disqus_username: steveafrost

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: about me
    url: /about

# projects in header index
projects:
  - name: PJ Masks Live
    url: http://pjmaskslive.com
  - name: Daily Documentary
    url: https://github.com/steveafrost/daily-documentary
  - name: Plant Nanny
    url: https://github.com/steveafrost/plant-nanny

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
