# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steve Frost
tagline: Portfolio & Blogs of Steve Frost, aspiring developer and avid learner.
email: ffrostt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Operations & Support Manager (and aspiring developer) with a thirst for knowledge and a passion for working with technology-forward teams. Known best for organizing data, flexing interpersonal skills, and showing compassion for end-users.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://steveafrost.com" # the base hostname & protocol for your site
permalink: pretty
twitter_username: steveeff
github_username:  steveafrost

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from