# Site settings
title: Steve Frost - Full Stack Web Developer
description: "Full-Stack Web Developmer with a thirst for knowledge and a passion for working with technology-forward teams. Known best for organizing massive amounts of data, flexing interpersonal skills, and showing compassion for end-users."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://steveafrost.com" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https:yourusername.githu.io'

# User settings
username: Steve Frost
user_title: Full Stack Web Developer
email: ffrostt@gmail.com
twitter_username: SteveEff
github_username:  steveafrost
disqus_username: steveafrost

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: about me
    url: /about

# projects in header index
projects:
  - name: Daily Documentary
    url: https://github.com/steveafrost/daily-documentary
  - name: Plant Nanny
    url: https://github.com/steveafrost/plant-nanny
  - name: Scoreboard CLI Gem
    url: https://github.com/steveafrost/scoreboard-cli-gem

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
