# Permalinks
#
permalink:           pretty

# Setup
title:               Steve Frost
tagline:             'Blogs of an aspiring developer and avid learner.'
description:         'Operations & Support Manager (and aspiring developer) with a thirst for knowledge and a passion for working with technology-forward teams. Known best for organizing data, flexing interpersonal skills, and showing compassion for end-users.'
url:                 http://steveafrost.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Steve Frost
  url:               https://twitter.com/steveeff
  email:             ffrostt@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
